### ISSUE TITLE
Was this really created in 2019?

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/di-ecdsa-secpr1-2019#1]
Just wondering, since I don't remember this showing up anywhere except recently.

**Comment by clehner** [comment]
`EcdsaSecp256r1Signature2019` was in the VC Data Model base context in 2019, e.g.: https://github.com/w3c/vc-data-model/blob/df99d22f24a08cee1c65f7930f06baa44f4d516e/CR/2019-07-25/contexts/credentials/v1#L124-L161
But I didn't see a spec for it before this one (https://github.com/w3c-ccg/community/issues/228).
I did not find mention of `EcdsaSecp384r1Signature2019` before this spec.

**Comment by peacekeeper** [comment]
Okay I guess the presence in the context means that it has already existed in some form back then. Good enough for me, thanks for finding this. Closing.
